import streamlit as st
from datetime import datetime

PLATFORM_POSITIONING = {
    'en': 'This is an AI Data Science Statistical Probability Analysis Service, NOT a gambling platform. All predictions are generated by mathematical models for analytical and entertainment purposes only.',
    'zh_hant': '本平台為 AI 數據科學統計概率分析服務，並非賭博平台。所有預測均由數學模型生成，僅供分析及娛樂用途。',
    'zh_hans': '本平台为 AI 数据科学统计概率分析服务，并非赌博平台。所有预测均由数学模型生成，仅供分析及娱乐用途。',
}

REQUIRED_CHECKBOXES = [
    {
        'en': 'I confirm I am 18 years of age or older',
        'zh_hant': '我確認我已年滿18歲',
        'zh_hans': '我确认我已年满18岁',
    },
    {
        'en': 'I understand this is NOT a gambling platform and I will NOT use it for gambling purposes',
        'zh_hant': '我明白本平台並非賭博平台，我不會將其用於賭博用途',
        'zh_hans': '我明白本平台并非赌博平台，我不会将其用于赌博用途',
    },
    {
        'en': 'I understand predictions are statistical probabilities, not guaranteed outcomes',
        'zh_hant': '我明白預測結果為統計概率，並非保證結果',
        'zh_hans': '我明白预测结果为统计概率，并非保证结果',
    },
    {
        'en': "I agree to the platform's Terms of Service and Privacy Policy",
        'zh_hant': '我同意本平台的服務條款及私隱政策',
        'zh_hans': '我同意本平台的服务条款及隐私政策',
    },
]

JURISDICTION_DISCLAIMERS = {
    'china': [
        ('刑法第303條', '根据《中华人民共和国刑法》第三百零三条，以营利为目的开设赌场或聚众赌博属违法行为。本平台不提供任何赌博服务，不收取任何投注，不支付任何奖金。违反者将承担刑事责任。'),
        ('PIPL', '根据《中华人民共和国个人信息保护法》，您的个人信息仅用于提供服务，未经同意不会向第三方共享。我们遵守数据本地化要求。'),
        ('未成年人保护', '根据《中华人民共和国未成年人保护法》，本平台禁止未满18周岁的未成年人使用。未成年人不得访问本平台的任何预测功能。'),
        ('AI生成内容标识', '根据《生成式人工智能服务管理暂行办法》，AI生成内容需明确标识。本平台所有预测均由AI模型生成，不构成任何建议。'),
    ],
    'hong_kong': [
        ('賭博條例Cap 148', '根據香港《賭博條例》（第148章），未經許可的博彩活動屬違法行為。本平台不是賭博中介，不提供投注服務，不收取任何賭注。'),
        ('PDPO', '根據《個人資料（私隱）條例》，您的個人資料僅用於提供服務，未經同意不會向第三方披露。'),
    ],
    'eu': [
        ('AI Act', 'Per EU AI Act Article 52, this AI system is classified as limited-risk. Predictions are generated by AI and must not be treated as guaranteed outcomes. Transparency disclosure is provided as required.'),
        ('GDPR', 'Your data is processed in accordance with GDPR. You have the right to access, rectify, and delete your personal data. Data may be processed outside the EU with appropriate safeguards.'),
    ],
    'usa': [
        ('First Amendment', 'This platform provides statistical analysis and commentary protected under the First Amendment of the US Constitution as commercial speech. It does not constitute gambling activity as defined by federal law (Wire Act, UIGEA).'),
        ('Non-gambling', 'This is an information service providing statistical probability analysis. It does not accept bets, wagers, or facilitate gambling transactions. Users are solely responsible for their actions.'),
    ],
    'other': [
        ('Anti-gambling', 'This platform does not provide gambling services, does not accept bets or wagers, and does not pay out any winnings. All predictions are statistical analyses for informational and entertainment purposes only.'),
        ('Data Privacy', 'Your personal data is processed securely and only used to provide the service. It will not be shared with third parties without your consent.'),
        ('AI Transparency', 'All predictions on this platform are generated by AI mathematical models. They represent statistical probabilities and should not be interpreted as guaranteed outcomes or professional advice.'),
    ],
}

JURISDICTION_OPTIONS = {
    'international': [
        ('china', '🇨🇳 China'),
        ('hong_kong', '🇭🇰 Hong Kong'),
        ('eu', '🇪🇺 European Union'),
        ('usa', '🇺🇸 United States'),
        ('other', '🌍 Other'),
    ],
    'china': [
        ('china', '🇨🇳 中国'),
        ('hong_kong', '🇭🇰 香港'),
        ('eu', '🇪🇺 欧盟'),
        ('usa', '🇺🇸 美国'),
        ('other', '🌍 其他'),
    ],
}

_CONSENT_CSS = """
<style>
    .consent-gate-wrapper {
        display: flex;
        justify-content: center;
        align-items: center;
        min-height: 100vh;
        padding: 2rem;
    }
    .consent-gate-card {
        max-width: 720px;
        width: 100%;
        background-color: #1E1E1E;
        border-radius: 12px;
        padding: 2.5rem;
        box-shadow: 0 4px 24px rgba(0,0,0,0.4);
    }
    .consent-positioning {
        background: linear-gradient(135deg, #4CAF50, #2E7D32);
        border-radius: 8px;
        padding: 1.25rem 1.5rem;
        margin-bottom: 1.5rem;
        text-align: center;
    }
    .consent-positioning p {
        color: #FFFFFF;
        font-size: 1.05rem;
        font-weight: 600;
        margin: 0;
        line-height: 1.6;
    }
    .consent-disclaimer-card {
        background-color: #2C2C2C;
        border-radius: 8px;
        padding: 1rem 1.25rem;
        margin-bottom: 0.75rem;
        border-left: 3px solid #FFB300;
    }
    .consent-disclaimer-card h4 {
        color: #FFB300;
        margin: 0 0 0.4rem 0;
        font-size: 0.95rem;
    }
    .consent-disclaimer-card p {
        color: #B0BEC5;
        margin: 0;
        font-size: 0.88rem;
        line-height: 1.55;
    }
    .consent-warning {
        background-color: rgba(239,83,80,0.12);
        border: 1px solid #EF5350;
        border-radius: 8px;
        padding: 0.75rem 1rem;
        color: #EF5350;
        text-align: center;
        margin-top: 1rem;
        font-size: 0.9rem;
    }
</style>
"""

def show_consent_gate(app_version: str = 'international') -> bool:
    if st.session_state.get('consent_accepted', False):
        return True

    lang = 'zh_hans' if app_version == 'china' else 'en'

    st.markdown(_CONSENT_CSS, unsafe_allow_html=True)

    st.markdown('<div class="consent-gate-wrapper">', unsafe_allow_html=True)
    st.markdown('<div class="consent-gate-card">', unsafe_allow_html=True)

    positioning_text = PLATFORM_POSITIONING.get(lang, PLATFORM_POSITIONING['en'])
    st.markdown(
        f'<div class="consent-positioning"><p>{positioning_text}</p></div>',
        unsafe_allow_html=True,
    )

    options = JURISDICTION_OPTIONS.get(app_version, JURISDICTION_OPTIONS['international'])
    option_labels = [label for _, label in options]
    option_keys = [key for key, _ in options]

    select_label = '选择您所在的地区' if app_version == 'china' else 'Select your jurisdiction / region'
    selected_label = st.selectbox(select_label, option_labels)
    selected_jurisdiction = option_keys[option_labels.index(selected_label)]

    disclaimers = JURISDICTION_DISCLAIMERS.get(selected_jurisdiction, JURISDICTION_DISCLAIMERS['other'])
    for title, text in disclaimers:
        st.markdown(
            f'<div class="consent-disclaimer-card"><h4>{title}</h4><p>{text}</p></div>',
            unsafe_allow_html=True,
        )

    st.markdown('<div style="margin-top:1.5rem;"></div>', unsafe_allow_html=True)

    checkbox_states = []
    for i, cb in enumerate(REQUIRED_CHECKBOXES):
        label = cb.get(lang, cb['en'])
        checked = st.checkbox(label, key=f'consent_cb_{i}')
        checkbox_states.append(checked)

    all_checked = all(checkbox_states)

    if not all_checked and any(checkbox_states):
        warning_text = '⚠️ 請勾選所有確認項目方可繼續' if lang == 'zh_hans' else '⚠️ Please check all boxes to continue'
        st.markdown(f'<div class="consent-warning">{warning_text}</div>', unsafe_allow_html=True)

    enter_label = '进入' if app_version == 'china' else 'Enter'
    if st.button(enter_label, disabled=not all_checked, use_container_width=True):
        st.session_state.consent_accepted = True
        st.session_state.consent_timestamp = datetime.now().isoformat()
        st.session_state.consent_jurisdiction = selected_jurisdiction
        st.rerun()

    st.markdown('</div>', unsafe_allow_html=True)
    st.markdown('</div>', unsafe_allow_html=True)

    return False
