DISCLAIMERS = {
    'prediction': {
        'default': 'This prediction is for entertainment and analytical purposes only. It does not constitute financial or betting advice. Past performance does not guarantee future results.',
        'china': '本預測僅供娛樂和數據分析用途，不構成任何財務或投注建議。過往表現不代表未來結果。',
        'hong_kong': '本預測僅供娛樂和數據分析用途，不構成任何財務或投注建議。過往表現不代表未來結果。',
        'eu': 'This forecast is for entertainment and analytical purposes only. It does not constitute financial advice. AI-generated predictions must be verified independently per EU AI Act transparency requirements.',
        'uk': 'This prediction is for entertainment and analytical purposes only. It does not constitute financial advice under FCA guidelines.',
        'us': 'This prediction is for entertainment purposes only. Not intended as betting or financial advice.',
        'japan': 'この予測は娯楽・分析目的のみです。金融・投資アドバイスではありません。',
        'south_korea': '본 예측은 오락 및 분석 목적으로만 제공됩니다. 재무 또는 투자 조언이 아닙니다.',
        'singapore': 'This prediction is for entertainment and analytical purposes only. It does not constitute financial advice.',
    },
    'anti_gambling': {
        'default': 'This app does not promote, facilitate, or endorse gambling. All predictions are statistical analyses for entertainment purposes.',
        'china': '本應用不推廣、不促進、不認可任何形式的博彩活動。所有預測均為統計分析，僅供娛樂用途。',
        'hong_kong': '本應用不推廣、不促進、不認可任何形式的博彩活動。所有預測均為統計分析，僅供娛樂用途。根據香港《賭博條例》，未經許可的博彩活動屬違法行為。',
        'eu': 'This app does not promote, facilitate, or endorse gambling. All predictions are statistical analyses for entertainment purposes. Compliant with EU AI Act transparency requirements.',
        'uk': 'This app does not promote, facilitate, or endorse gambling. All predictions are statistical analyses for entertainment purposes. Compliant with UK Gambling Act 2005.',
        'us': 'This app does not promote, facilitate, or endorse gambling. All predictions are statistical analyses for entertainment purposes only.',
        'japan': '当アプリはギャンブルを推奨・促進・是認するものではありません。',
        'south_korea': '본 앱은 도박을 장려, 촉진 또는 인정하지 않습니다. 모든 예측은 통계 분석으로 오락 목적입니다.',
        'singapore': 'This app does not promote, facilitate, or endorse gambling. All predictions are statistical analyses for entertainment purposes.',
    },
    'data_privacy': {
        'default': 'Your data is processed securely and not shared with third parties without consent.',
        'china': '根據《個人信息保護法》，您的個人信息僅用於提供服務，未經同意不會向第三方共享。我們遵守數據本地化要求。',
        'hong_kong': '根據《個人資料（私隱）條例》，您的個人資料僅用於提供服務，未經同意不會向第三方披露。',
        'eu': 'Your data is processed in accordance with GDPR. You have the right to access, rectify, and delete your personal data. Data may be processed outside the EU with appropriate safeguards.',
        'uk': 'Your data is processed in accordance with UK GDPR. You have the right to access, rectify, and delete your personal data.',
        'us': 'Your data is processed securely. California residents may exercise CCPA rights regarding their personal information.',
        'japan': 'お客様のデータは安全に処理され、同意なく第三者と共有されることはありません。',
        'south_korea': '개인정보는 안전하게 처리되며 동의 없이 제3자와 공유되지 않습니다.',
        'singapore': 'Your data is processed securely under PDPA. We do not share your data with third parties without consent.',
    },
    'ai_transparency': {
        'default': 'Predictions are generated by an AI model (FormulaV9) and should not be treated as guaranteed outcomes.',
        'china': '預測由 AI 模型（FormulaV9）生成，不應被視為確定結果。根據《生成式人工智能服務管理暫行辦法》，AI 生成內容需明確標識。',
        'hong_kong': '預測由 AI 模型（FormulaV9）生成，不應被視為確定結果。',
        'eu': 'Predictions are generated by an AI model (FormulaV9) and should not be treated as guaranteed outcomes. Per EU AI Act Article 52, this AI system is classified as limited-risk and requires transparency disclosure.',
        'uk': 'Predictions are generated by an AI model (FormulaV9) and should not be treated as guaranteed outcomes.',
        'us': 'Predictions are generated by an AI model (FormulaV9) and should not be treated as guaranteed outcomes.',
        'japan': '予測はAIモデル（FormulaV9）により生成されており、確実な結果として扱うべきではありません。',
        'south_korea': '예측은 AI 모델(FormulaV9)에 의해 생성되며 보장된 결과로 간주해서는 안 됩니다.',
        'singapore': 'Predictions are generated by an AI model (FormulaV9) and should not be treated as guaranteed outcomes.',
    },
}

VERSION_SPECIFIC = {
    'china': ['prediction', 'anti_gambling', 'data_privacy', 'ai_transparency'],
    'international': ['prediction', 'anti_gambling', 'data_privacy', 'ai_transparency'],
}


class DisclaimerEngine:
    def get_disclaimer(self, disclaimer_type: str, jurisdiction: str = 'other') -> str:
        disclaimers = DISCLAIMERS.get(disclaimer_type)
        if not disclaimers:
            return ''
        return disclaimers.get(jurisdiction, disclaimers.get('default', ''))

    def get_all_disclaimers(self, jurisdiction: str = 'other', app_version: str = 'international') -> list:
        types = VERSION_SPECIFIC.get(app_version, VERSION_SPECIFIC['international'])
        results = []
        for d_type in types:
            text = self.get_disclaimer(d_type, jurisdiction)
            if text:
                results.append({
                    'type': d_type,
                    'text': text,
                    'jurisdiction': jurisdiction,
                })
        return results

    def get_prediction_disclaimer(self, jurisdiction: str = 'other') -> str:
        return self.get_disclaimer('prediction', jurisdiction)

    def get_anti_gambling_notice(self, jurisdiction: str = 'other') -> str:
        return self.get_disclaimer('anti_gambling', jurisdiction)
