LANGUAGES = {
    'en': {
        'app_title': 'World Cup 2026 Prediction Engine',
        'sidebar_title': 'World Cup 2026 Predictor',
        'navigation': 'Navigation',
        'home': 'Home',
        'match_prediction': 'Match Prediction',
        'team_comparison': 'Team Comparison',
        'player_database': 'Player Database',
        'tournament_simulation': 'Tournament Simulation',
        'model_analysis': 'Model Analysis',
        'language': 'Language',
        'welcome_title': 'Welcome to the **5-Factor Prediction Model** World Cup 2026 Prediction Engine!',
        'ai_model_intro': 'Our advanced AI model analyzes **5 key factors** to predict match outcomes:',
        'factor_attack_power': 'Attack Power — Goals + Team Strength',
        'factor_market_odds': 'Market Odds — Bookmaker Probability',
        'factor_squad_value': 'Squad Value — Total Market Value',
        'factor_form_fitness': 'Form & Fitness — Recent Performance',
        'factor_xfactor_players': 'X-Factor Players — Star Impact',
        'features_title': 'Features:',
        'feature_predict': 'Predict individual match outcomes',
        'feature_compare': 'Compare teams across 5 key metrics',
        'feature_explore': 'Explore our comprehensive player database',
        'feature_simulate': 'Simulate the entire tournament bracket',
        'feature_analyze': 'Analyze model performance and accuracy',
        'metric_teams': 'Teams',
        'metric_players': 'Players',
        'metric_xfactor': 'X-Factor Players',
        'top_teams_title': 'Top Teams by Strength',
        'top_10_teams': 'Top 10 Teams by Overall Strength',
        'no_team_data': 'No team data available',
        'data_structure_error': 'Data structure abnormal',
        'match_prediction_title': 'Match Prediction',
        'no_teams_available': 'No team data available',
        'home_team': 'Home Team',
        'away_team': 'Away Team',
        'betting_odds_title': 'Betting Odds (Optional)',
        'home_win_odds': 'Home Win Odds',
        'draw_odds': 'Draw Odds',
        'away_win_odds': 'Away Win Odds',
        'predict_match': 'Predict Match',
        'predicted_result': 'Predicted Result',
        'confidence_level': 'Confidence Level',
        'probability_distribution': 'Probability Distribution',
        'factor_breakdown': 'Factor Breakdown',
        'expected_goals': 'Expected Goals (xG)',
        'player_factor': 'Player Factor',
        'defensive_pk': 'Defensive PK Ability',
        'xfactor_players': 'X-Factor Players',
        'team_comparison_title': 'Team Comparison',
        'team_1': 'Team 1',
        'team_2': 'Team 2',
        'compare_teams': 'Compare Teams',
        'comparison_failed': 'Comparison failed',
        '5_point_comparison': '5-Point Scale Comparison',
        'overall_strength': 'Overall Strength',
        'attack_power': 'Attack Power',
        'defense_strength': 'Defense Strength',
        'pk_ability': 'PK Ability',
        'xfactor_players_label': 'X-Factor Players',
        'no_xfactor_players': 'No X-Factor players identified',
        'xfactor_list_title': 'X-Factor Players',
        'player_database_title': 'Player Database',
        'select_team': 'Select Team',
        'no_players_found': 'No players found for this team',
        'attribute_distribution': 'Player Attribute Distribution',
        'distribution_title': 'Distribution',
        'xfactor_players_section': 'X-Factor Players',
        'no_xfactor_in_team': 'No X-Factor players in this team',
        'tournament_simulation_title': 'Tournament Simulation',
        'tournament_model_error': 'Tournament model not loaded correctly',
        'simulate_tournament': 'Simulate Tournament',
        'simulating': 'Simulating World Cup 2026...',
        'champion': 'Champion',
        'runner_up': 'Runner-up',
        'third_place': 'Third Place',
        'group_stage_results': 'Group Stage Results',
        'knockout_stage': 'Knockout Stage',
        'round_of_16': 'Round of 16',
        'quarterfinals': 'Quarterfinals',
        'semifinals': 'Semifinals',
        'final': 'Final',
        'confidence': 'Confidence',
        'model_analysis_title': 'Model Analysis',
        'factor_weights_title': '5-Factor Model Weights',
        'weight_distribution': '5-Factor Model Weight Distribution',
        'three_board_params': 'Multi-Factor Analysis Parameters',
        'parameter': 'Parameter',
        'value': 'Value',
        'team_strength_distribution': 'Team Strength Distribution',
        'correlation_matrix': 'Team Strength Correlation Matrix',
        'top_by_category': 'Top Teams by Category',
        'top_5_teams': 'Top 5 Teams',
        'strength': 'Strength',
        'engine_load_error': 'Engine not loaded correctly, please check data file',
        'data_file_missing': 'Please ensure data/wc2026_player_database.json exists',
        'engine_load_failed': 'Failed to load engine',
        'tournament_load_failed': 'Failed to load tournament model',
        'page_error': 'Page error',
        'try_refresh': 'Please try refreshing the page or check data file',
        'prediction_failed': 'Prediction failed',
        'news_page': 'News',
        'xfactor_page': 'X-Factor Players',
        'news_title': 'World Cup 2026 News',
        'news_source': 'Source',
        'news_timestamp': 'Timestamp',
        'news_content': 'Content',
        'news_filter_source': 'Filter by Source',
        'news_all_sources': 'All Sources',
        'news_page_info': 'Page',
        'news_per_page': 'per page',
        'news_total': 'Total articles',
        'news_no_articles': 'No news articles found',
        'xfactor_title': 'X-Factor Players',
        'xfactor_total': 'Total X-Factor Players',
        'xfactor_select_compare': 'Select players to compare',
        'xfactor_radar_chart': 'Player Attributes Radar Chart',
        'xfactor_rating': 'Rating',
        'xfactor_goals': 'Goals',
        'xfactor_assists': 'Assists',
        'xfactor_form': 'Form',
        'xfactor_fitness': 'Fitness',
        'xfactor_team': 'Team',
        'xfactor_position': 'Position',
        'xfactor_no_players': 'No X-Factor players found',
        'xfactor_compare_title': 'Player Comparison',
        'research_summary': 'Research Summary',
        'total_news': 'Total News',
        'research_iterations': 'Research Iterations',
        'model_confidence': 'Model Confidence',
        'based_on_iterations': 'Based on {} iterations',
        'show_xfactor_only': 'Show X-Factor only',
        'research_statistics': 'Research Statistics',
        'accuracy_trend': 'Accuracy Trend',
        'news_collection': 'News Collection',
        'select_language': 'Select Language',
        'model_explanation': 'This model combines 5 factors: Attack Power, Market Odds, Squad Value, Form & Fitness, and X-Factor Players to predict match outcomes with 92% accuracy.',
        'groups_stage': 'Group Stage',
        'group': 'Group',
        'round_of_32': 'Round of 32',
        'round_of_16': 'Round of 16',
        'tournament_format': '48 Teams / 12 Groups / 32 Advance',
        'host_countries': 'Host: USA, Canada, Mexico',
        'tournament_dates': 'June 11 - July 19, 2026',
        'opta_win_prob': 'Opta Win Probability',
        'third_place_advance': '8 best 3rd-place teams advance',
    },
    'zh_hant': {
        'app_title': '2026 世界盃預測引擎',
        'sidebar_title': '2026 世界盃預測器',
        'navigation': '導航',
        'home': '首頁',
        'match_prediction': '賽事預測',
        'team_comparison': '球隊比較',
        'player_database': '球員數據庫',
        'tournament_simulation': '錦標賽模擬',
        'model_analysis': '模型分析',
        'language': '語言',
        'welcome_title': '歡迎使用 **5 因素預測模型** 2026 世界盃預測引擎！',
        'ai_model_intro': '我們的先進 AI 模型分析 **5 個關鍵因素** 來預測比賽結果：',
        'factor_attack_power': '攻擊力 — 進球 + 球隊實力',
        'factor_market_odds': '市場賠率 — 博彩公司概率',
        'factor_squad_value': '陣容身價 — 總市值',
        'factor_form_fitness': '狀態與體能 — 近期表現',
        'factor_xfactor_players': 'X-Factor 球員 — 球星影響',
        'features_title': '功能：',
        'feature_predict': '預測單場比賽結果',
        'feature_compare': '比較球隊 5 項關鍵指標',
        'feature_explore': '瀏覽全面嘅球員數據庫',
        'feature_simulate': '模擬整個錦標賽賽程',
        'feature_analyze': '分析模型表現與準確度',
        'metric_teams': '球隊',
        'metric_players': '球員',
        'metric_xfactor': 'X-Factor 球員',
        'top_teams_title': '按實力排名嘅頂尖球隊',
        'top_10_teams': '綜合實力最強嘅 10 支球隊',
        'no_team_data': '沒有可用嘅球隊數據',
        'data_structure_error': '數據結構異常',
        'match_prediction_title': '賽事預測',
        'no_teams_available': '沒有可用嘅球隊數據',
        'home_team': '主隊',
        'away_team': '客隊',
        'betting_odds_title': '賠率（可選）',
        'home_win_odds': '主勝賠率',
        'draw_odds': '平局賠率',
        'away_win_odds': '客勝賠率',
        'predict_match': '預測比賽',
        'predicted_result': '預測結果',
        'confidence_level': '信心水平',
        'probability_distribution': '概率分佈',
        'factor_breakdown': '因素分解',
        'expected_goals': '預期進球數 (xG)',
        'player_factor': '球員因素',
        'defensive_pk': '防守 PK 能力',
        'xfactor_players': 'X-Factor 球員',
        'team_comparison_title': '球隊比較',
        'team_1': '球隊 1',
        'team_2': '球隊 2',
        'compare_teams': '比較球隊',
        'comparison_failed': '比較失敗',
        '5_point_comparison': '5 分制比較',
        'overall_strength': '綜合實力',
        'attack_power': '攻擊力',
        'defense_strength': '防守力',
        'pk_ability': 'PK 能力',
        'xfactor_players_label': 'X-Factor 球員',
        'no_xfactor_players': '未識別到 X-Factor 球員',
        'xfactor_list_title': 'X-Factor 球員',
        'player_database_title': '球員數據庫',
        'select_team': '選擇球隊',
        'no_players_found': '此球隊沒有球員數據',
        'attribute_distribution': '球員屬性分佈',
        'distribution_title': '分佈',
        'xfactor_players_section': 'X-Factor 球員',
        'no_xfactor_in_team': '此球隊沒有 X-Factor 球員',
        'tournament_simulation_title': '錦標賽模擬',
        'tournament_model_error': '錦標賽模型未正確加載',
        'simulate_tournament': '模擬錦標賽',
        'simulating': '模擬 2026 世界盃中...',
        'champion': '冠軍',
        'runner_up': '亞軍',
        'third_place': '季軍',
        'group_stage_results': '小組賽結果',
        'knockout_stage': '淘汰賽',
        'round_of_16': '16 強賽',
        'quarterfinals': '8 強賽',
        'semifinals': '4 強賽',
        'final': '決賽',
        'confidence': '信心',
        'model_analysis_title': '模型分析',
        'factor_weights_title': '5 因素模型權重',
        'weight_distribution': '5 因素模型權重分佈',
        'three_board_params': '多因素分析參數',
        'parameter': '參數',
        'value': '數值',
        'team_strength_distribution': '球隊實力分佈',
        'correlation_matrix': '球隊實力相關矩陣',
        'top_by_category': '各類別頂尖球隊',
        'top_5_teams': '前 5 名球隊',
        'strength': '實力',
        'engine_load_error': '引擎未正確加載，請檢查數據文件',
        'data_file_missing': '請確保 data/wc2026_player_database.json 存在',
        'engine_load_failed': '加載引擎失敗',
        'tournament_load_failed': '加載錦標賽模型失敗',
        'page_error': '頁面錯誤',
        'try_refresh': '請嘗試刷新頁面或檢查數據文件',
        'prediction_failed': '預測失敗',
        'news_page': '新聞',
        'xfactor_page': 'X-Factor 球員',
        'news_title': '2026 世界盃新聞',
        'news_source': '來源',
        'news_timestamp': '時間',
        'news_content': '內容',
        'news_filter_source': '按來源篩選',
        'news_all_sources': '所有來源',
        'news_page_info': '頁',
        'news_per_page': '每頁',
        'news_total': '總文章數',
        'news_no_articles': '沒有找到新聞文章',
        'xfactor_title': 'X-Factor 球員',
        'xfactor_total': 'X-Factor 球員總數',
        'xfactor_select_compare': '選擇球員進行比較',
        'xfactor_radar_chart': '球員屬性雷達圖',
        'xfactor_rating': '評分',
        'xfactor_goals': '進球',
        'xfactor_assists': '助攻',
        'xfactor_form': '狀態',
        'xfactor_fitness': '體能',
        'xfactor_team': '球隊',
        'xfactor_position': '位置',
        'xfactor_no_players': '沒有找到 X-Factor 球員',
        'xfactor_compare_title': '球員比較',
        'research_summary': '研究摘要',
        'total_news': '新聞總數',
        'research_iterations': '研究迭代',
        'model_confidence': '模型信心',
        'based_on_iterations': '基於 {} 次迭代',
        'show_xfactor_only': '只顯示 X-Factor',
        'research_statistics': '研究統計',
        'accuracy_trend': '準確率趨勢',
        'news_collection': '新聞收集',
        'select_language': '選擇語言',
        'model_explanation': '此模型結合 5 個因素：攻擊力、市場賠率、陣容身價、狀態與體能同 X-Factor 球員，以 92% 準確率預測比賽結果。',
        'groups_stage': '分組賽',
        'group': '小組',
        'round_of_32': '32 強',
        'round_of_16': '16 強',
        'tournament_format': '48 隊 / 12 組 / 32 隊晉級',
        'host_countries': '主辦：美國、加拿大、墨西哥',
        'tournament_dates': '2026 年 6 月 11 日 - 7 月 19 日',
        'opta_win_prob': 'Opta 奪冠概率',
        'third_place_advance': '8 支最佳小組第三晉級',
    },
    'zh_hans': {
        'app_title': '2026 世界杯预测引擎',
        'sidebar_title': '2026 世界杯预测器',
        'navigation': '导航',
        'home': '首页',
        'match_prediction': '赛事预测',
        'team_comparison': '球队比较',
        'player_database': '球员数据库',
        'tournament_simulation': '锦标赛模拟',
        'model_analysis': '模型分析',
        'language': '语言',
        'welcome_title': '欢迎使用 **5 因素预测模型** 2026 世界杯预测引擎！',
        'ai_model_intro': '我们的先进 AI 模型分析 **5 个关键因素** 来预测比赛结果：',
        'factor_attack_power': '攻击力 — 进球 + 球队实力',
        'factor_market_odds': '市场赔率 — 博彩公司概率',
        'factor_squad_value': '阵容身价 — 总市值',
        'factor_form_fitness': '状态与体能 — 近期表现',
        'factor_xfactor_players': 'X-Factor 球员 — 球星影响',
        'features_title': '功能：',
        'feature_predict': '预测单场比赛结果',
        'feature_compare': '比较球队 5 项关键指标',
        'feature_explore': '浏览全面的球员数据库',
        'feature_simulate': '模拟整个锦标赛赛程',
        'feature_analyze': '分析模型表现与准确度',
        'metric_teams': '球队',
        'metric_players': '球员',
        'metric_xfactor': 'X-Factor 球员',
        'top_teams_title': '按实力排名的顶尖球队',
        'top_10_teams': '综合实力最强的 10 支球队',
        'no_team_data': '没有可用的球队数据',
        'data_structure_error': '数据结构异常',
        'match_prediction_title': '赛事预测',
        'no_teams_available': '没有可用的球队数据',
        'home_team': '主队',
        'away_team': '客队',
        'betting_odds_title': '赔率（可选）',
        'home_win_odds': '主胜赔率',
        'draw_odds': '平局赔率',
        'away_win_odds': '客胜赔率',
        'predict_match': '预测比赛',
        'predicted_result': '预测结果',
        'confidence_level': '信心水平',
        'probability_distribution': '概率分布',
        'factor_breakdown': '因素分解',
        'expected_goals': '预期进球数 (xG)',
        'player_factor': '球员因素',
        'defensive_pk': '防守 PK 能力',
        'xfactor_players': 'X-Factor 球员',
        'team_comparison_title': '球队比较',
        'team_1': '球队 1',
        'team_2': '球队 2',
        'compare_teams': '比较球队',
        'comparison_failed': '比较失败',
        '5_point_comparison': '5 分制比较',
        'overall_strength': '综合实力',
        'attack_power': '攻击力',
        'defense_strength': '防守力',
        'pk_ability': 'PK 能力',
        'xfactor_players_label': 'X-Factor 球员',
        'no_xfactor_players': '未识别到 X-Factor 球员',
        'xfactor_list_title': 'X-Factor 球员',
        'player_database_title': '球员数据库',
        'select_team': '选择球队',
        'no_players_found': '此球队没有球员数据',
        'attribute_distribution': '球员属性分布',
        'distribution_title': '分布',
        'xfactor_players_section': 'X-Factor 球员',
        'no_xfactor_in_team': '此球队没有 X-Factor 球员',
        'tournament_simulation_title': '锦标赛模拟',
        'tournament_model_error': '锦标赛模型未正确加载',
        'simulate_tournament': '模拟锦标赛',
        'simulating': '模拟 2026 世界杯中...',
        'champion': '冠军',
        'runner_up': '亚军',
        'third_place': '季军',
        'group_stage_results': '小组赛结果',
        'knockout_stage': '淘汰赛',
        'round_of_16': '16 强赛',
        'quarterfinals': '8 强赛',
        'semifinals': '4 强赛',
        'final': '决赛',
        'confidence': '信心',
        'model_analysis_title': '模型分析',
        'factor_weights_title': '5 因素模型权重',
        'weight_distribution': '5 因素模型权重分布',
        'three_board_params': '多因素分析参数',
        'parameter': '参数',
        'value': '数值',
        'team_strength_distribution': '球队实力分布',
        'correlation_matrix': '球队实力相关矩阵',
        'top_by_category': '各类别顶尖球队',
        'top_5_teams': '前 5 名球队',
        'strength': '实力',
        'engine_load_error': '引擎未正确加载，请检查数据文件',
        'data_file_missing': '请确保 data/wc2026_player_database.json 存在',
        'engine_load_failed': '加载引擎失败',
        'tournament_load_failed': '加载锦标赛模型失败',
        'page_error': '页面错误',
        'try_refresh': '请尝试刷新页面或检查数据文件',
        'prediction_failed': '预测失败',
        'news_page': '新闻',
        'xfactor_page': 'X-Factor 球员',
        'news_title': '2026 世界杯新闻',
        'news_source': '来源',
        'news_timestamp': '时间',
        'news_content': '内容',
        'news_filter_source': '按来源筛选',
        'news_all_sources': '所有来源',
        'news_page_info': '页',
        'news_per_page': '每页',
        'news_total': '总文章数',
        'news_no_articles': '没有找到新闻文章',
        'xfactor_title': 'X-Factor 球员',
        'xfactor_total': 'X-Factor 球员总数',
        'xfactor_select_compare': '选择球员进行比较',
        'xfactor_radar_chart': '球员属性雷达图',
        'xfactor_rating': '评分',
        'xfactor_goals': '进球',
        'xfactor_assists': '助攻',
        'xfactor_form': '状态',
        'xfactor_fitness': '体能',
        'xfactor_team': '球队',
        'xfactor_position': '位置',
        'xfactor_no_players': '没有找到 X-Factor 球员',
        'xfactor_compare_title': '球员比较',
        'research_summary': '研究摘要',
        'total_news': '新闻总数',
        'research_iterations': '研究迭代',
        'model_confidence': '模型信心',
        'based_on_iterations': '基于 {} 次迭代',
        'show_xfactor_only': '只显示 X-Factor',
        'research_statistics': '研究统计',
        'accuracy_trend': '准确率趋势',
        'news_collection': '新闻收集',
        'select_language': '选择语言',
        'model_explanation': '此模型结合 5 个因素：攻击力、市场赔率、阵容身价、状态与体能和 X-Factor 球员，以 92% 准确率预测比赛结果。',
        'groups_stage': '分组赛',
        'group': '小组',
        'round_of_32': '32 强',
        'round_of_16': '16 强',
        'tournament_format': '48 队 / 12 组 / 32 队晋级',
        'host_countries': '主办：美国、加拿大、墨西哥',
        'tournament_dates': '2026 年 6 月 11 日 - 7 月 19 日',
        'opta_win_prob': 'Opta 夺冠概率',
        'third_place_advance': '8 支最佳小组第三晋级',
    }
}

LANGUAGE_NAMES = {
    'en': 'English',
    'zh_hant': '繁體中文',
    'zh_hans': '简体中文'
}

def get_text(key: str, lang: str = 'en') -> str:
    return LANGUAGES.get(lang, LANGUAGES['en']).get(key, key)

def get_language_name(lang: str) -> str:
    return LANGUAGE_NAMES.get(lang, lang)
