LANGUAGES = {
    'en': {
        'app_title': 'World Cup 2026 Prediction Engine',
        'sidebar_title': 'World Cup 2026 Predictor',
        'navigation': 'Navigation',
        'home': 'Home',
        'match_prediction': 'Match Prediction',
        'team_comparison': 'Team Comparison',
        'player_database': 'Player Database',
        'tournament_simulation': 'Tournament Simulation',
        'model_analysis': 'Model Analysis',
        'language': 'Language',
        'welcome_title': 'Welcome to the **Formula V9** World Cup 2026 Prediction Engine!',
        'ai_model_intro': 'Our advanced AI model analyzes **7 key factors** to predict match outcomes:',
        'factor_xg': 'Expected Goals (xG) - Attacking potency vs defensive strength',
        'factor_v7': 'V7 Base Model - Core team strength comparison',
        'factor_odds': 'Odds Composite - Market sentiment analysis',
        'factor_player': 'Player Factor - Team composition and fitness',
        'factor_pk': 'Defensive PK Ability - Penalty shootout preparedness',
        'factor_sub': 'Substitution Effect - Bench strength impact',
        'factor_xfactor': 'X-Factor Players - Game-changing talent',
        'features_title': 'Features:',
        'feature_predict': 'Predict individual match outcomes',
        'feature_compare': 'Compare teams across 5 key metrics',
        'feature_explore': 'Explore our comprehensive player database',
        'feature_simulate': 'Simulate the entire tournament bracket',
        'feature_analyze': 'Analyze model performance and accuracy',
        'metric_teams': 'Teams',
        'metric_players': 'Players',
        'metric_xfactor': 'X-Factor Players',
        'top_teams_title': 'Top Teams by Strength',
        'top_10_teams': 'Top 10 Teams by Overall Strength',
        'no_team_data': 'No team data available',
        'data_structure_error': 'Data structure abnormal',
        'match_prediction_title': 'Match Prediction',
        'no_teams_available': 'No team data available',
        'home_team': 'Home Team',
        'away_team': 'Away Team',
        'betting_odds_title': 'Betting Odds (Optional)',
        'home_win_odds': 'Home Win Odds',
        'draw_odds': 'Draw Odds',
        'away_win_odds': 'Away Win Odds',
        'predict_match': 'Predict Match',
        'predicted_result': 'Predicted Result',
        'confidence_level': 'Confidence Level',
        'probability_distribution': 'Probability Distribution',
        'factor_breakdown': 'Factor Breakdown',
        'expected_goals': 'Expected Goals (xG)',
        'player_factor': 'Player Factor',
        'defensive_pk': 'Defensive PK Ability',
        'xfactor_players': 'X-Factor Players',
        'team_comparison_title': 'Team Comparison',
        'team_1': 'Team 1',
        'team_2': 'Team 2',
        'compare_teams': 'Compare Teams',
        'comparison_failed': 'Comparison failed',
        '5_point_comparison': '5-Point Scale Comparison',
        'overall_strength': 'Overall Strength',
        'attack_power': 'Attack Power',
        'defense_strength': 'Defense Strength',
        'pk_ability': 'PK Ability',
        'xfactor_players_label': 'X-Factor Players',
        'no_xfactor_players': 'No X-Factor players identified',
        'xfactor_list_title': 'X-Factor Players',
        'player_database_title': 'Player Database',
        'select_team': 'Select Team',
        'no_players_found': 'No players found for this team',
        'attribute_distribution': 'Player Attribute Distribution',
        'distribution_title': 'Distribution',
        'xfactor_players_section': 'X-Factor Players',
        'no_xfactor_in_team': 'No X-Factor players in this team',
        'tournament_simulation_title': 'Tournament Simulation',
        'tournament_model_error': 'Tournament model not loaded correctly',
        'simulate_tournament': 'Simulate Tournament',
        'simulating': 'Simulating World Cup 2026...',
        'champion': 'Champion',
        'runner_up': 'Runner-up',
        'third_place': 'Third Place',
        'group_stage_results': 'Group Stage Results',
        'knockout_stage': 'Knockout Stage',
        'round_of_16': 'Round of 16',
        'quarterfinals': 'Quarterfinals',
        'semifinals': 'Semifinals',
        'final': 'Final',
        'confidence': 'Confidence',
        'model_analysis_title': 'Model Analysis',
        'factor_weights_title': 'Formula V9 Factor Weights',
        'weight_distribution': 'Formula V9 Factor Weight Distribution',
        'three_board_params': 'Three Board Model Parameters',
        'parameter': 'Parameter',
        'value': 'Value',
        'team_strength_distribution': 'Team Strength Distribution',
        'correlation_matrix': 'Team Strength Correlation Matrix',
        'top_by_category': 'Top Teams by Category',
        'top_5_teams': 'Top 5 Teams',
        'strength': 'Strength',
        'engine_load_error': 'Engine not loaded correctly, please check data file',
        'data_file_missing': 'Please ensure data/wc2026_player_database.json exists',
        'engine_load_failed': 'Failed to load engine',
        'tournament_load_failed': 'Failed to load tournament model',
        'page_error': 'Page error',
        'try_refresh': 'Please try refreshing the page or check data file',
        'prediction_failed': 'Prediction failed',
    },
    'zh_hant': {
        'app_title': '2026 世界盃預測引擎',
        'sidebar_title': '2026 世界盃預測器',
        'navigation': '導航',
        'home': '首頁',
        'match_prediction': '賽事預測',
        'team_comparison': '球隊比較',
        'player_database': '球員數據庫',
        'tournament_simulation': '錦標賽模擬',
        'model_analysis': '模型分析',
        'language': '語言',
        'welcome_title': '歡迎使用 **Formula V9** 2026 世界盃預測引擎！',
        'ai_model_intro': '我們的先進 AI 模型分析 **7 個關鍵因素** 來預測比賽結果：',
        'factor_xg': '預期進球數 (xG) — 攻擊力對防守強度',
        'factor_v7': 'V7 基礎模型 — 核心球隊實力比較',
        'factor_odds': '賠率綜合 — 市場情緒分析',
        'factor_player': '球員因素 — 球隊組成與體能狀況',
        'factor_pk': '防守 PK 能力 — 互射十二碼準備度',
        'factor_sub': '換人效應 — 後備深度影響',
        'factor_xfactor': 'X-Factor 球員 — 改變比賽嘅天才',
        'features_title': '功能：',
        'feature_predict': '預測單場比賽結果',
        'feature_compare': '比較球隊 5 項關鍵指標',
        'feature_explore': '瀏覽全面嘅球員數據庫',
        'feature_simulate': '模擬整個錦標賽賽程',
        'feature_analyze': '分析模型表現與準確度',
        'metric_teams': '球隊',
        'metric_players': '球員',
        'metric_xfactor': 'X-Factor 球員',
        'top_teams_title': '按實力排名嘅頂尖球隊',
        'top_10_teams': '綜合實力最強嘅 10 支球隊',
        'no_team_data': '沒有可用嘅球隊數據',
        'data_structure_error': '數據結構異常',
        'match_prediction_title': '賽事預測',
        'no_teams_available': '沒有可用嘅球隊數據',
        'home_team': '主隊',
        'away_team': '客隊',
        'betting_odds_title': '賠率（可選）',
        'home_win_odds': '主勝賠率',
        'draw_odds': '平局賠率',
        'away_win_odds': '客勝賠率',
        'predict_match': '預測比賽',
        'predicted_result': '預測結果',
        'confidence_level': '信心水平',
        'probability_distribution': '概率分佈',
        'factor_breakdown': '因素分解',
        'expected_goals': '預期進球數 (xG)',
        'player_factor': '球員因素',
        'defensive_pk': '防守 PK 能力',
        'xfactor_players': 'X-Factor 球員',
        'team_comparison_title': '球隊比較',
        'team_1': '球隊 1',
        'team_2': '球隊 2',
        'compare_teams': '比較球隊',
        'comparison_failed': '比較失敗',
        '5_point_comparison': '5 分制比較',
        'overall_strength': '綜合實力',
        'attack_power': '攻擊力',
        'defense_strength': '防守力',
        'pk_ability': 'PK 能力',
        'xfactor_players_label': 'X-Factor 球員',
        'no_xfactor_players': '未識別到 X-Factor 球員',
        'xfactor_list_title': 'X-Factor 球員',
        'player_database_title': '球員數據庫',
        'select_team': '選擇球隊',
        'no_players_found': '此球隊沒有球員數據',
        'attribute_distribution': '球員屬性分佈',
        'distribution_title': '分佈',
        'xfactor_players_section': 'X-Factor 球員',
        'no_xfactor_in_team': '此球隊沒有 X-Factor 球員',
        'tournament_simulation_title': '錦標賽模擬',
        'tournament_model_error': '錦標賽模型未正確加載',
        'simulate_tournament': '模擬錦標賽',
        'simulating': '模擬 2026 世界盃中...',
        'champion': '冠軍',
        'runner_up': '亞軍',
        'third_place': '季軍',
        'group_stage_results': '小組賽結果',
        'knockout_stage': '淘汰賽',
        'round_of_16': '16 強賽',
        'quarterfinals': '8 強賽',
        'semifinals': '4 強賽',
        'final': '決賽',
        'confidence': '信心',
        'model_analysis_title': '模型分析',
        'factor_weights_title': 'Formula V9 因素權重',
        'weight_distribution': 'Formula V9 因素權重分佈',
        'three_board_params': '三板模型參數',
        'parameter': '參數',
        'value': '數值',
        'team_strength_distribution': '球隊實力分佈',
        'correlation_matrix': '球隊實力相關矩陣',
        'top_by_category': '各類別頂尖球隊',
        'top_5_teams': '前 5 名球隊',
        'strength': '實力',
        'engine_load_error': '引擎未正確加載，請檢查數據文件',
        'data_file_missing': '請確保 data/wc2026_player_database.json 存在',
        'engine_load_failed': '加載引擎失敗',
        'tournament_load_failed': '加載錦標賽模型失敗',
        'page_error': '頁面錯誤',
        'try_refresh': '請嘗試刷新頁面或檢查數據文件',
        'prediction_failed': '預測失敗',
    },
    'zh_hans': {
        'app_title': '2026 世界杯预测引擎',
        'sidebar_title': '2026 世界杯预测器',
        'navigation': '导航',
        'home': '首页',
        'match_prediction': '赛事预测',
        'team_comparison': '球队比较',
        'player_database': '球员数据库',
        'tournament_simulation': '锦标赛模拟',
        'model_analysis': '模型分析',
        'language': '语言',
        'welcome_title': '欢迎使用 **Formula V9** 2026 世界杯预测引擎！',
        'ai_model_intro': '我们的先进 AI 模型分析 **7 个关键因素** 来预测比赛结果：',
        'factor_xg': '预期进球数 (xG) — 攻击力对防守强度',
        'factor_v7': 'V7 基础模型 — 核心球队实力比较',
        'factor_odds': '赔率综合 — 市场情绪分析',
        'factor_player': '球员因素 — 球队组成与体能状况',
        'factor_pk': '防守 PK 能力 — 互射十二码准备度',
        'factor_sub': '换人效应 — 后备深度影响',
        'factor_xfactor': 'X-Factor 球员 — 改变比赛的天才',
        'features_title': '功能：',
        'feature_predict': '预测单场比赛结果',
        'feature_compare': '比较球队 5 项关键指标',
        'feature_explore': '浏览全面的球员数据库',
        'feature_simulate': '模拟整个锦标赛赛程',
        'feature_analyze': '分析模型表现与准确度',
        'metric_teams': '球队',
        'metric_players': '球员',
        'metric_xfactor': 'X-Factor 球员',
        'top_teams_title': '按实力排名的顶尖球队',
        'top_10_teams': '综合实力最强的 10 支球队',
        'no_team_data': '没有可用的球队数据',
        'data_structure_error': '数据结构异常',
        'match_prediction_title': '赛事预测',
        'no_teams_available': '没有可用的球队数据',
        'home_team': '主队',
        'away_team': '客队',
        'betting_odds_title': '赔率（可选）',
        'home_win_odds': '主胜赔率',
        'draw_odds': '平局赔率',
        'away_win_odds': '客胜赔率',
        'predict_match': '预测比赛',
        'predicted_result': '预测结果',
        'confidence_level': '信心水平',
        'probability_distribution': '概率分布',
        'factor_breakdown': '因素分解',
        'expected_goals': '预期进球数 (xG)',
        'player_factor': '球员因素',
        'defensive_pk': '防守 PK 能力',
        'xfactor_players': 'X-Factor 球员',
        'team_comparison_title': '球队比较',
        'team_1': '球队 1',
        'team_2': '球队 2',
        'compare_teams': '比较球队',
        'comparison_failed': '比较失败',
        '5_point_comparison': '5 分制比较',
        'overall_strength': '综合实力',
        'attack_power': '攻击力',
        'defense_strength': '防守力',
        'pk_ability': 'PK 能力',
        'xfactor_players_label': 'X-Factor 球员',
        'no_xfactor_players': '未识别到 X-Factor 球员',
        'xfactor_list_title': 'X-Factor 球员',
        'player_database_title': '球员数据库',
        'select_team': '选择球队',
        'no_players_found': '此球队没有球员数据',
        'attribute_distribution': '球员属性分布',
        'distribution_title': '分布',
        'xfactor_players_section': 'X-Factor 球员',
        'no_xfactor_in_team': '此球队没有 X-Factor 球员',
        'tournament_simulation_title': '锦标赛模拟',
        'tournament_model_error': '锦标赛模型未正确加载',
        'simulate_tournament': '模拟锦标赛',
        'simulating': '模拟 2026 世界杯中...',
        'champion': '冠军',
        'runner_up': '亚军',
        'third_place': '季军',
        'group_stage_results': '小组赛结果',
        'knockout_stage': '淘汰赛',
        'round_of_16': '16 强赛',
        'quarterfinals': '8 强赛',
        'semifinals': '4 强赛',
        'final': '决赛',
        'confidence': '信心',
        'model_analysis_title': '模型分析',
        'factor_weights_title': 'Formula V9 因素权重',
        'weight_distribution': 'Formula V9 因素权重分布',
        'three_board_params': '三板模型参数',
        'parameter': '参数',
        'value': '数值',
        'team_strength_distribution': '球队实力分布',
        'correlation_matrix': '球队实力相关矩阵',
        'top_by_category': '各类别顶尖球队',
        'top_5_teams': '前 5 名球队',
        'strength': '实力',
        'engine_load_error': '引擎未正确加载，请检查数据文件',
        'data_file_missing': '请确保 data/wc2026_player_database.json 存在',
        'engine_load_failed': '加载引擎失败',
        'tournament_load_failed': '加载锦标赛模型失败',
        'page_error': '页面错误',
        'try_refresh': '请尝试刷新页面或检查数据文件',
        'prediction_failed': '预测失败',
    }
}

LANGUAGE_NAMES = {
    'en': 'English',
    'zh_hant': '繁體中文',
    'zh_hans': '简体中文'
}

def get_text(key: str, lang: str = 'en') -> str:
    return LANGUAGES.get(lang, LANGUAGES['en']).get(key, key)

def get_language_name(lang: str) -> str:
    return LANGUAGE_NAMES.get(lang, lang)
